import type {
  Application,
  Company,
  CompanyUserAccess,
  Franchise,
  Job,
  Profile,
  SiteContent,
} from '../types';

const now = new Date().toISOString();
const demoPublishedAt = new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString();
const expiresAt = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();

const companyDistributionDefaults = {
  legal_name: null,
  same_as_url: null,
};

const jobDistributionDefaults = {
  published_at: demoPublishedAt,
  expires_at: expiresAt,
  distribution_google_enabled: true,
  distribution_indeed_enabled: false,
  distribution_glassdoor_enabled: false,
  distribution_infojobs_enabled: false,
  external_apply_url: null,
  direct_apply: true,
  country: 'BR',
  street_address: null,
  postal_code: null,
  salary_min: null,
  salary_max: null,
  salary_currency: 'BRL',
  salary_unit: 'MONTH',
  seo_title: null,
  seo_description: null,
  responsible_name: 'Equipe de Recrutamento',
  open_positions: 1,
  approved_positions: 0,
  process_status: 'in_progress' as const,
  internal_notes: null,
  billing_amount: 2800,
  billing_type: 'fixed' as const,
  billing_status: 'pending' as const,
  billing_due_date: null,
  finance_responsible: 'Financeiro People Jobs',
  franchise_commission: 20,
};

const applicationProcessDefaults = {
  stage: 'qualificacao' as const,
  kanban_order: 0,
  match_score: null,
  adhesion_score: null,
  is_new: true,
  rejection_reason: null,
  tags: [],
  interview_scheduled_at: null,
  recruiter_opinion: null,
  professional_summary: null,
  skills: [],
  education: [],
  experiences: [],
  resume_analysis_status: 'pending' as const,
  resume_analysis: {
    professional_summary: '', skills: [], education: [], experiences: [], languages: [], certifications: [],
    total_experience_months: 0, current_role: '', location: '', salary_expectation_found: '', availability_found: '', evidence: [],
  },
  resume_analysis_error: null,
  resume_analyzed_at: null,
  ai_match_score: null,
  ranking_details: {
    overall_score: 0, mandatory_requirements_score: 0, experience_score: 0, technical_skills_score: 0,
    education_score: 0, location_score: 0, availability_score: 0, salary_score: 0,
    behavioral_indicators_score: 0, met_requirements: [], missing_requirements: [], strengths: [], risks: [], evidence: [], summary: '',
  },
  ranking_generated_at: null,
  resume_analysis_waived_at: null,
  resume_analysis_waiver_reason: null,
  resume_analysis_waived_by: null,
};

export const mockFranchises: Franchise[] = [
  {
    id: 'f1111111-1111-4111-8111-111111111111',
    name: 'Unidade Matriz',
    slug: 'unidade-matriz',
    legal_name: 'Redde People Jobs',
    document: null,
    contact_name: 'Gestor da Unidade',
    contact_email: 'unidade@peoplejobs.com.br',
    contact_phone: null,
    city: 'São Luís',
    state: 'MA',
    status: 'active',
    created_at: now,
    updated_at: now,
  },
];

const companyFranchiseDefaults = {
  franchise_id: mockFranchises[0].id,
  commercial_status: 'active_client' as const,
  franchise: mockFranchises[0],
};

export const mockCompanies: Company[] = [
  {
    id: '11111111-1111-4111-8111-111111111111',
    ...companyFranchiseDefaults,
    name: 'Aba Kids',
    slug: 'aba-kids',
    logo_url: '/imagens/clientes/aba-kids.png',
    cover_image_url: null,
    segment: 'Educação infantil e desenvolvimento',
    city: 'São Luís',
    state: 'MA',
    employees_range: '51-200',
    website_url: 'https://example.com',
    ...companyDistributionDefaults,
    instagram_url: 'https://instagram.com',
    linkedin_url: 'https://linkedin.com',
    short_description: 'Centro de educação infantil com oportunidades em atendimento, apoio pedagógico, recreação e rotinas da unidade.',
    about_text:
      'A Aba Kids atua no cuidado e desenvolvimento de crianças, integrando acolhimento às famílias, apoio pedagógico e organização de rotinas educativas.',
    why_work_here: 'Ambiente orientado por cuidado, aprendizado e desenvolvimento infantil, com funções claras e contato próximo com famílias.',
    culture_text: 'Cultura de acolhimento, responsabilidade, colaboração e atenção ao desenvolvimento das crianças.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '22222222-2222-4222-8222-222222222222',
    ...companyFranchiseDefaults,
    name: 'Aquarela',
    slug: 'aquarela',
    logo_url: '/imagens/clientes/aquarela.png',
    cover_image_url: null,
    segment: 'Educação e atividades criativas',
    city: 'São Luís',
    state: 'MA',
    employees_range: '11-50',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Empresa de serviços educacionais com oportunidades em atendimento, apoio administrativo e suporte à rotina pedagógica.',
    about_text: 'A Aquarela atua no segmento educacional, unindo organização, criatividade e atendimento próximo para apoiar alunos, famílias e equipe pedagógica.',
    why_work_here: 'Processo seletivo estruturado, rotina organizada e espaço para profissionais que gostam de educação e relacionamento com famílias.',
    culture_text: 'Cultura de cuidado, criatividade, colaboração e melhoria contínua.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '33333333-3333-4333-8333-333333333333',
    ...companyFranchiseDefaults,
    name: 'Conceito',
    slug: 'conceito',
    logo_url: '/imagens/clientes/conceito.png',
    cover_image_url: null,
    segment: 'Engenharia civil e elétrica',
    city: 'São Luís',
    state: 'MA',
    employees_range: '201-500',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Empresa de engenharia civil e elétrica com oportunidades em obras, projetos, manutenção, administrativo e apoio técnico.',
    about_text:
      'A Conceito atua com soluções de engenharia civil e elétrica, apoiando projetos, instalações, manutenções e acompanhamento técnico com foco em qualidade e segurança.',
    why_work_here: 'Rotina técnica estruturada, contato com projetos reais e oportunidades para perfis de campo, escritório e suporte operacional.',
    culture_text: 'Cultura de segurança, precisão, colaboração e compromisso com a qualidade das entregas.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '44444444-4444-4444-8444-444444444444',
    ...companyFranchiseDefaults,
    name: 'Farma Center',
    slug: 'farma-center',
    logo_url: '/imagens/clientes/farma-center.png',
    cover_image_url: null,
    segment: 'Farmácia de manipulação e drogaria',
    city: 'São Luís',
    state: 'MA',
    employees_range: '101-200',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Farmácia de manipulação e drogaria com oportunidades em atendimento, laboratório, dispensação, estoque e suporte administrativo.',
    about_text: 'A Farma Center atua no varejo farmacêutico e em manipulação, conectando cuidado, orientação ao cliente, preparo de fórmulas e rotina operacional organizada.',
    why_work_here: 'Ambiente voltado à saúde, com processos definidos e oportunidades para quem valoriza precisão, cuidado e atendimento responsável.',
    culture_text: 'Cultura de responsabilidade sanitária, atenção ao cliente, ética e cuidado.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '55555555-5555-4555-8555-555555555555',
    ...companyFranchiseDefaults,
    name: 'Karolícias',
    slug: 'karolicias',
    logo_url: '/imagens/clientes/karolicias.png',
    cover_image_url: null,
    segment: 'Alimentos e confeitaria',
    city: 'São Luís',
    state: 'MA',
    employees_range: '51-200',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Marca de alimentos e confeitaria com oportunidades em produção, atendimento, vendas e rotinas operacionais.',
    about_text: 'A Karolícias atua no segmento de alimentos, com foco em produtos bem apresentados, atendimento acolhedor e operação cuidadosa do preparo à entrega.',
    why_work_here: 'Ambiente prático, rotina clara e oportunidades para quem gosta de atendimento, produção artesanal e cuidado com detalhes.',
    culture_text: 'Cultura orientada por qualidade, capricho, colaboração e melhoria diária.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '66666666-6666-4666-8666-666666666666',
    ...companyFranchiseDefaults,
    name: 'Levive',
    slug: 'levive',
    logo_url: '/imagens/clientes/levive.png',
    cover_image_url: null,
    segment: 'Saúde, estética e bem-estar',
    city: 'São Luís',
    state: 'MA',
    employees_range: '201-500',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Empresa de saúde, estética e bem-estar com oportunidades em atendimento, comercial, procedimentos e suporte à operação.',
    about_text: 'A Levive atua com serviços voltados à saúde, estética e bem-estar, combinando atendimento consultivo, cuidado com o cliente e rotinas de qualidade.',
    why_work_here: 'Plano de crescimento por área, liderança próxima e rotinas de treinamento para profissionais de atendimento, vendas e operação.',
    culture_text: 'Ambiente acolhedor, disciplinado e orientado por cuidado, qualidade e evolução profissional.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
];

export const mockJobs: Job[] = [
  {
    id: 'aaaaaaa1-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
    franchise_id: mockFranchises[0].id,
    company_id: mockCompanies[0].id,
    title: 'Assistente de Atendimento Infantil',
    slug: 'assistente-de-atendimento-infantil',
    short_description: 'Atendimento a famílias, organização de demandas e suporte à rotina da unidade.',
    description:
      'Atuar no atendimento a famílias, registrar solicitações, organizar informações e apoiar a liderança em rotinas operacionais.',
    about_job:
      'Vaga para atuar no suporte à rotina de atendimento infantil, com foco em organização, acolhimento e comunicação com famílias.',
    responsibilities: 'Atender famílias; registrar solicitações; acompanhar prazos; apoiar relatórios operacionais.',
    requirements: 'Ensino médio completo; boa comunicação; experiência com atendimento ou educação será diferencial.',
    desirable_requirements: 'Experiência com rotina escolar; facilidade com sistemas de atendimento; perfil organizado.',
    benefits: 'Vale-transporte; vale-alimentação; plano de desenvolvimento interno.',
    salary_range: 'R$ 1.600 a R$ 1.900',
    neighborhood: 'Renascença',
    city: 'São Luís',
    state: 'MA',
    modality: 'presencial',
    contract_type: 'clt',
    seniority: 'Júnior',
    education_level: 'Ensino médio - Completo',
    work_schedule: 'Para atuação em horário comercial.',
    about_company:
      'A Aba Kids atua com serviços voltados ao desenvolvimento infantil, combinando atendimento cuidadoso, rotina organizada e equipes preparadas.',
    status: 'open',
    is_featured: true,
    application_deadline: null,
    ...jobDistributionDefaults,
    salary_min: 1600,
    salary_max: 1900,
    created_at: now,
    updated_at: now,
    company: mockCompanies[0],
  },
  {
    id: 'aaaaaaa2-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
    franchise_id: mockFranchises[0].id,
    company_id: mockCompanies[1].id,
    title: 'Assistente Administrativo',
    slug: 'assistente-administrativo',
    short_description: 'Controle de documentos, indicadores e suporte às rotinas financeiras.',
    description:
      'Responsável por organizar documentos, acompanhar indicadores, apoiar processos financeiros e dar suporte à gestão.',
    about_job:
      'Vaga para apoiar rotinas administrativas e financeiras, mantendo documentos, controles e indicadores organizados.',
    responsibilities: 'Organizar documentos; apoiar contas a pagar; acompanhar indicadores; preparar relatórios.',
    requirements: 'Experiência administrativa; Excel intermediário; perfil organizado e analítico.',
    desirable_requirements: 'Vivência com rotinas financeiras; noções de indicadores; familiaridade com sistemas de gestão.',
    benefits: 'Vale-alimentação; assistência médica; bonificação por desempenho.',
    salary_range: 'R$ 2.200 a R$ 2.700',
    neighborhood: 'Cohama',
    city: 'São Luís',
    state: 'MA',
    modality: 'hibrido',
    contract_type: 'clt',
    seniority: 'Pleno',
    education_level: 'Ensino médio - Completo',
    work_schedule: 'Para atuação em horário comercial.',
    about_company: 'A Aquarela é uma empresa parceira com rotinas estruturadas, foco em atendimento e desenvolvimento de pessoas.',
    status: 'open',
    is_featured: true,
    application_deadline: null,
    ...jobDistributionDefaults,
    salary_min: 2200,
    salary_max: 2700,
    created_at: now,
    updated_at: now,
    company: mockCompanies[1],
  },
  {
    id: 'aaaaaaa3-aaaa-4aaa-8aaa-aaaaaaaaaaa3',
    franchise_id: mockFranchises[0].id,
    company_id: mockCompanies[4].id,
    title: 'Atendente de Loja',
    slug: 'atendente-de-loja',
    short_description: 'Atendimento ao cliente, organização de pedidos e apoio à rotina comercial.',
    description:
      'Atuar no atendimento aos clientes da Karolícias, apoiar pedidos, manter a organização do espaço e contribuir para uma experiência acolhedora.',
    about_job:
      'Vaga para atendimento em loja, com contato direto com clientes, apoio aos pedidos e organização do ambiente.',
    responsibilities: 'Atender clientes; organizar pedidos; apoiar exposição de produtos; manter o padrão de atendimento.',
    requirements: 'Boa comunicação, organização, disponibilidade de horário e interesse pelo segmento de alimentos.',
    desirable_requirements: 'Experiência anterior em loja; facilidade com vendas; vivência com atendimento presencial.',
    benefits: 'Vale-transporte; alimentação no local; treinamento interno.',
    salary_range: 'R$ 1.500 a R$ 1.900',
    neighborhood: 'Centro',
    city: 'São Luís',
    state: 'MA',
    modality: 'presencial',
    contract_type: 'clt',
    seniority: 'Operacional',
    education_level: 'Ensino médio - Completo',
    work_schedule: 'Para atuação em horário comercial.',
    about_company: 'A Karolícias atua no segmento de alimentos com foco em qualidade, apresentação, atendimento e ritmo operacional.',
    status: 'open',
    is_featured: true,
    application_deadline: null,
    ...jobDistributionDefaults,
    salary_min: 1500,
    salary_max: 1900,
    created_at: now,
    updated_at: now,
    company: mockCompanies[4],
  },
  {
    id: 'aaaaaaa4-aaaa-4aaa-8aaa-aaaaaaaaaaa4',
    franchise_id: mockFranchises[0].id,
    company_id: mockCompanies[3].id,
    title: 'Recepcionista',
    slug: 'recepcionista',
    short_description: 'Recepção de clientes, organização de agenda e suporte à rotina de atendimento.',
    description:
      'Recepcionar clientes da Farma Center, organizar agenda, registrar informações e apoiar o fluxo de atendimento.',
    about_job:
      'Vaga para recepção presencial, organização de agenda, acolhimento de clientes e suporte ao fluxo de atendimento.',
    responsibilities: 'Recepcionar clientes; organizar agenda; confirmar horários; apoiar rotinas administrativas.',
    requirements: 'Ensino médio completo; boa comunicação; experiência com recepção será diferencial.',
    desirable_requirements: 'Experiência em clínica ou estética; noções de caixa; conhecimento básico em sistemas de agenda.',
    benefits: 'Vale-transporte; bonificação; treinamento interno.',
    salary_range: 'R$ 1.600 a R$ 2.000',
    neighborhood: 'Calhau',
    city: 'São Luís',
    state: 'MA',
    modality: 'presencial',
    contract_type: 'clt',
    seniority: 'Operacional',
    education_level: 'Ensino médio - Completo',
    work_schedule: 'Para atuação em horário comercial.',
    about_company: 'A Farma Center atua no varejo farmacêutico e em manipulação, conectando cuidado, orientação ao cliente, preparo de fórmulas e rotina operacional organizada.',
    status: 'open',
    is_featured: false,
    application_deadline: null,
    ...jobDistributionDefaults,
    salary_min: 1600,
    salary_max: 2000,
    created_at: now,
    updated_at: now,
    company: mockCompanies[3],
  },
];

export const mockApplications: Application[] = [
  {
    ...applicationProcessDefaults,
    id: 'bbbbbbb1-bbbb-4bbb-8bbb-bbbbbbbbbbb1',
    franchise_id: mockFranchises[0].id,
    job_id: mockJobs[0].id,
    company_id: mockCompanies[0].id,
    candidate_name: 'Mariana Costa',
    candidate_email: 'mariana@example.com',
    candidate_phone: '(98) 99999-0001',
    candidate_city: 'São Luís, MA',
    linkedin_url: null,
    portfolio_url: null,
    salary_expectation: 'R$ 1.900',
    availability: 'Imediata',
    message: 'Tenho experiência com atendimento presencial e canais digitais.',
    resume_file_path: 'applications/local/mariana-costa.pdf',
    status: 'novo',
    adhesion_score: 91,
    match_score: 88,
    tags: ['Atendimento', 'Disponível'],
    professional_summary:
      'Profissional de atendimento com experiência em acolhimento de famílias, organização de demandas e comunicação multicanal.',
    skills: ['Atendimento ao cliente', 'Organização', 'Comunicação', 'Pacote Office'],
    education: [
      {
        course: 'Pedagogia',
        institution: 'Universidade Estadual do Maranhão',
        level: 'Graduação',
        status: 'Cursando',
        start_year: 2023,
        end_year: null,
      },
    ],
    experiences: [
      {
        role: 'Assistente de atendimento',
        company: 'Espaço Aprender',
        start_date: '2024-02-01',
        end_date: null,
        current: true,
        description: 'Atendimento a responsáveis, controle de agenda e apoio à equipe pedagógica.',
      },
    ],
    lgpd_consent: true,
    source: 'portal_publico',
    created_at: now,
    updated_at: now,
    job: mockJobs[0],
    company: mockCompanies[0],
  },
  {
    ...applicationProcessDefaults,
    stage: 'qualificacao',
    is_new: false,
    id: 'bbbbbbb2-bbbb-4bbb-8bbb-bbbbbbbbbbb2',
    franchise_id: mockFranchises[0].id,
    job_id: mockJobs[2].id,
    company_id: mockCompanies[4].id,
    candidate_name: 'Rafael Lima',
    candidate_email: 'rafael@example.com',
    candidate_phone: '(98) 98888-0002',
    candidate_city: 'São Luís, MA',
    linkedin_url: 'https://linkedin.com',
    portfolio_url: 'https://portfolio.example.com',
    salary_expectation: 'R$ 1.900',
    availability: '30 dias',
    message: 'Tenho experiência com atendimento ao cliente e organização de pedidos.',
    resume_file_path: 'applications/local/rafael-lima.pdf',
    status: 'em_analise',
    adhesion_score: 84,
    match_score: 79,
    tags: ['Vendas', 'Experiência'],
    lgpd_consent: true,
    source: 'portal_publico',
    created_at: now,
    updated_at: now,
    job: mockJobs[2],
    company: mockCompanies[4],
  },
  {
    ...applicationProcessDefaults,
    id: 'bbbbbbb3-bbbb-4bbb-8bbb-bbbbbbbbbbb3',
    franchise_id: mockFranchises[0].id,
    job_id: mockJobs[0].id,
    company_id: mockCompanies[0].id,
    candidate_name: 'Carlos Henrique',
    candidate_email: 'carlos.henrique@example.com',
    candidate_phone: '(98) 98771-2301',
    candidate_city: 'São Luís, MA',
    linkedin_url: 'https://linkedin.com/in/carlos-henrique',
    portfolio_url: null,
    salary_expectation: 'R$ 1.850',
    availability: 'Imediata',
    message: 'Experiência com atendimento a famílias e organização de rotinas.',
    resume_file_path: 'applications/local/carlos-henrique.pdf',
    status: 'triagem',
    stage: 'qualificacao',
    kanban_order: 1,
    adhesion_score: 87,
    match_score: 85,
    is_new: false,
    tags: ['Comunicação', 'Organização'],
    lgpd_consent: true,
    source: 'linkedin',
    created_at: now,
    updated_at: now,
    job: mockJobs[0],
    company: mockCompanies[0],
  },
  {
    ...applicationProcessDefaults,
    id: 'bbbbbbb4-bbbb-4bbb-8bbb-bbbbbbbbbbb4',
    franchise_id: mockFranchises[0].id,
    job_id: mockJobs[0].id,
    company_id: mockCompanies[0].id,
    candidate_name: 'Beatriz Sousa',
    candidate_email: 'beatriz.sousa@example.com',
    candidate_phone: '(98) 99120-4402',
    candidate_city: 'Paço do Lumiar, MA',
    linkedin_url: null,
    portfolio_url: null,
    salary_expectation: 'R$ 1.900',
    availability: '15 dias',
    message: 'Atuação anterior em escola e atendimento ao público.',
    resume_file_path: 'applications/local/beatriz-sousa.pdf',
    status: 'teste',
    stage: 'testes',
    adhesion_score: 82,
    match_score: 80,
    is_new: false,
    tags: ['Educação', 'Teste enviado'],
    lgpd_consent: true,
    source: 'portal_publico',
    created_at: now,
    updated_at: now,
    job: mockJobs[0],
    company: mockCompanies[0],
  },
  {
    ...applicationProcessDefaults,
    id: 'bbbbbbb5-bbbb-4bbb-8bbb-bbbbbbbbbbb5',
    franchise_id: mockFranchises[0].id,
    job_id: mockJobs[0].id,
    company_id: mockCompanies[0].id,
    candidate_name: 'Joana Ribeiro',
    candidate_email: 'joana.ribeiro@example.com',
    candidate_phone: '(98) 98217-9083',
    candidate_city: 'São José de Ribamar, MA',
    linkedin_url: 'https://linkedin.com/in/joana-ribeiro',
    portfolio_url: null,
    salary_expectation: 'R$ 1.950',
    availability: 'Imediata',
    message: 'Perfil acolhedor, organizado e com experiência em recepção.',
    resume_file_path: 'applications/local/joana-ribeiro.pdf',
    status: 'entrevista',
    stage: 'entrevista',
    interview_scheduled_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    recruiter_opinion: 'Boa comunicação, postura acolhedora e experiência compatível com o atendimento da unidade.',
    adhesion_score: 94,
    match_score: 90,
    is_new: false,
    tags: ['Entrevista agendada', 'Destaque'],
    lgpd_consent: true,
    source: 'indicacao',
    created_at: now,
    updated_at: now,
    job: mockJobs[0],
    company: mockCompanies[0],
  },
  {
    ...applicationProcessDefaults,
    id: 'bbbbbbb6-bbbb-4bbb-8bbb-bbbbbbbbbbb6',
    franchise_id: mockFranchises[0].id,
    job_id: mockJobs[0].id,
    company_id: mockCompanies[0].id,
    candidate_name: 'Lucas Almeida',
    candidate_email: 'lucas.almeida@example.com',
    candidate_phone: '(98) 99801-6674',
    candidate_city: 'São Luís, MA',
    linkedin_url: 'https://linkedin.com/in/lucas-almeida',
    portfolio_url: null,
    salary_expectation: 'R$ 1.900',
    availability: 'Imediata',
    message: 'Experiência sólida em atendimento e bom relacionamento com famílias.',
    resume_file_path: 'applications/local/lucas-almeida.pdf',
    status: 'selecionado',
    stage: 'finalistas',
    adhesion_score: 96,
    match_score: 93,
    is_new: false,
    tags: ['Finalista', 'Referências ok'],
    lgpd_consent: true,
    source: 'infojobs',
    created_at: now,
    updated_at: now,
    job: mockJobs[0],
    company: mockCompanies[0],
  },
  {
    ...applicationProcessDefaults,
    id: 'bbbbbbb7-bbbb-4bbb-8bbb-bbbbbbbbbbb7',
    franchise_id: mockFranchises[0].id,
    job_id: mockJobs[0].id,
    company_id: mockCompanies[0].id,
    candidate_name: 'Ana Paula Mendes',
    candidate_email: 'ana.mendes@example.com',
    candidate_phone: '(98) 99251-1180',
    candidate_city: 'São Luís, MA',
    linkedin_url: null,
    portfolio_url: null,
    salary_expectation: 'R$ 1.900',
    availability: 'Imediata',
    message: 'Experiência em atendimento infantil e suporte administrativo.',
    resume_file_path: 'applications/local/ana-paula-mendes.pdf',
    status: 'contratado',
    stage: 'contratacao',
    adhesion_score: 98,
    match_score: 95,
    is_new: false,
    tags: ['Aprovada', 'Documentação'],
    lgpd_consent: true,
    source: 'portal_publico',
    created_at: now,
    updated_at: now,
    job: mockJobs[0],
    company: mockCompanies[0],
  },
];

export const mockProfiles: Profile[] = [
  {
    id: 'ccccccc1-cccc-4ccc-8ccc-ccccccccccc1',
    franchise_id: null,
    full_name: 'Administrador People Jobs',
    email: 'admin@peoplejobs.com.br',
    role: 'redde_super_admin',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'ccccccc2-cccc-4ccc-8ccc-ccccccccccc2',
    franchise_id: mockFranchises[0].id,
    full_name: 'Gestor Aba Kids',
    email: 'gestor@abakids.com.br',
    role: 'company_admin',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'ccccccc3-cccc-4ccc-8ccc-ccccccccccc3',
    franchise_id: mockFranchises[0].id,
    full_name: 'Recrutador Cliente',
    email: 'talentos@abakids.com.br',
    role: 'company_recruiter',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];

export const mockAccess: CompanyUserAccess[] = [
  {
    id: 'ddddddd1-dddd-4ddd-8ddd-ddddddddddd1',
    user_id: mockProfiles[1].id,
    company_id: mockCompanies[0].id,
    can_edit_company_page: true,
    can_manage_jobs: true,
    can_view_applications: true,
    can_download_resumes: true,
    created_at: now,
  },
  {
    id: 'ddddddd2-dddd-4ddd-8ddd-ddddddddddd2',
    user_id: mockProfiles[2].id,
    company_id: mockCompanies[0].id,
    can_edit_company_page: false,
    can_manage_jobs: true,
    can_view_applications: true,
    can_download_resumes: true,
    created_at: now,
  },
];

export const mockSiteContents: SiteContent[] = [
  {
    id: 'eeeeeee1-eeee-4eee-8eee-eeeeeeeeeee1',
    key: 'home_hero',
    title: 'Encontre oportunidades em empresas que contratam com mais critério.',
    subtitle:
      'O People Jobs conecta candidatos a empresas parceiras com processos de seleção mais claros, organizados e profissionais.',
    body: 'Veja vagas abertas em empresas parceiras do People Jobs e envie seu currículo de forma simples, rápida e segura.',
    button_label: 'Buscar vagas',
    button_url: '/vagas',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'eeeeeee2-eeee-4eee-8eee-eeeeeeeeeee2',
    key: 'home_company_cta',
    title: 'Sua empresa quer contratar com mais critério?',
    subtitle:
      'O People Jobs estrutura processos de contratação para reduzir improviso, rotatividade e decisões baseadas apenas em currículo.',
    body: null,
    button_label: 'Falar com a People Jobs',
    button_url: 'mailto:contato@peoplejobs.com.br',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];
