import type {
  Application,
  Company,
  CompanyUserAccess,
  Franchise,
  Job,
  Profile,
  SiteContent,
} from '../types';

const now = new Date().toISOString();
const expiresAt = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();

const companyDistributionDefaults = {
  legal_name: null,
  same_as_url: null,
};

const jobDistributionDefaults = {
  published_at: now,
  expires_at: expiresAt,
  distribution_google_enabled: true,
  distribution_indeed_enabled: false,
  distribution_glassdoor_enabled: false,
  distribution_infojobs_enabled: false,
  external_apply_url: null,
  direct_apply: true,
  country: 'BR',
  street_address: null,
  postal_code: null,
  salary_min: null,
  salary_max: null,
  salary_currency: 'BRL',
  salary_unit: 'MONTH',
  seo_title: null,
  seo_description: null,
  responsible_name: 'Equipe de Recrutamento',
  open_positions: 1,
  approved_positions: 0,
  process_status: 'in_progress' as const,
  internal_notes: null,
};

const applicationProcessDefaults = {
  stage: 'qualificacao' as const,
  kanban_order: 0,
  match_score: null,
  adhesion_score: null,
  is_new: true,
  rejection_reason: null,
  tags: [],
};

export const mockFranchises: Franchise[] = [
  {
    id: 'f1111111-1111-4111-8111-111111111111',
    name: 'Unidade Matriz',
    slug: 'unidade-matriz',
    legal_name: 'Redde People Jobs',
    document: null,
    contact_name: 'Gestor da Unidade',
    contact_email: 'unidade@peoplejobs.com.br',
    contact_phone: null,
    city: 'São Luís',
    state: 'MA',
    status: 'active',
    created_at: now,
    updated_at: now,
  },
];

const companyFranchiseDefaults = {
  franchise_id: mockFranchises[0].id,
  commercial_status: 'active_client' as const,
  franchise: mockFranchises[0],
};

export const mockCompanies: Company[] = [
  {
    id: '11111111-1111-4111-8111-111111111111',
    ...companyFranchiseDefaults,
    name: 'Aba Kids',
    slug: 'aba-kids',
    logo_url: '/imagens/clientes/aba-kids.png',
    cover_image_url: null,
    segment: 'Educação e desenvolvimento infantil',
    city: 'São Luís',
    state: 'MA',
    employees_range: '51-200',
    website_url: 'https://example.com',
    ...companyDistributionDefaults,
    instagram_url: 'https://instagram.com',
    linkedin_url: 'https://linkedin.com',
    short_description: 'Empresa parceira do People Jobs com oportunidades em atendimento, apoio pedagógico e operação.',
    about_text:
      'A Aba Kids atua com serviços voltados ao desenvolvimento infantil, combinando atendimento cuidadoso, rotina organizada e equipes preparadas.',
    why_work_here: 'Ambiente de crescimento, clareza de função e processo seletivo organizado com apoio do People Jobs.',
    culture_text: 'Cultura voltada para responsabilidade, cuidado, atendimento e desenvolvimento.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '22222222-2222-4222-8222-222222222222',
    ...companyFranchiseDefaults,
    name: 'Aquarela',
    slug: 'aquarela',
    logo_url: '/imagens/clientes/aquarela.png',
    cover_image_url: null,
    segment: 'Serviços educacionais',
    city: 'São Luís',
    state: 'MA',
    employees_range: '11-50',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Empresa parceira com vagas abertas para áreas administrativas, atendimento e operação.',
    about_text: 'A Aquarela é uma empresa parceira com rotinas estruturadas, foco em atendimento e desenvolvimento de pessoas.',
    why_work_here: 'Processo seletivo estruturado com apoio do People Jobs.',
    culture_text: 'Cultura focada em entrega, colaboração e melhoria contínua.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '33333333-3333-4333-8333-333333333333',
    ...companyFranchiseDefaults,
    name: 'Conceito',
    slug: 'conceito',
    logo_url: '/imagens/clientes/conceito.png',
    cover_image_url: null,
    segment: 'Serviços',
    city: 'São Luís',
    state: 'MA',
    employees_range: '201-500',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Empresa parceira com oportunidades em atendimento, rotinas comerciais e gestão operacional.',
    about_text:
      'A Conceito atua em serviços com foco em experiência do cliente, organização de processos e melhoria contínua.',
    why_work_here: 'Rotina clara, liderança próxima e oportunidades para perfis comerciais, administrativos e operacionais.',
    culture_text: 'Ambiente colaborativo, orientado por qualidade, ética e melhoria contínua.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '44444444-4444-4444-8444-444444444444',
    ...companyFranchiseDefaults,
    name: 'Darma Center',
    slug: 'darma-center',
    logo_url: '/imagens/clientes/darma-center.png',
    cover_image_url: null,
    segment: 'Saúde e bem-estar',
    city: 'São Luís',
    state: 'MA',
    employees_range: '101-200',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Centro parceiro com oportunidades em atendimento, recepção, operação e suporte administrativo.',
    about_text: 'O Darma Center reúne serviços com foco em bem-estar, atendimento humanizado e organização da experiência do cliente.',
    why_work_here: 'Processos bem definidos, rotina acolhedora e oportunidades para perfis de atendimento e suporte.',
    culture_text: 'Cultura de cuidado, pontualidade, acolhimento e responsabilidade.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '55555555-5555-4555-8555-555555555555',
    ...companyFranchiseDefaults,
    name: 'Karolícias',
    slug: 'karolicias',
    logo_url: '/imagens/clientes/karolicias.png',
    cover_image_url: null,
    segment: 'Alimentos',
    city: 'São Luís',
    state: 'MA',
    employees_range: '51-200',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Marca parceira com oportunidades em produção, atendimento, vendas e rotinas operacionais.',
    about_text: 'A Karolícias atua no segmento de alimentos com foco em qualidade, apresentação, atendimento e ritmo operacional.',
    why_work_here: 'Ambiente prático, rotina clara e oportunidades para quem gosta de atendimento e produção com capricho.',
    culture_text: 'Cultura orientada por qualidade, cuidado, colaboração e melhoria diária.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: '66666666-6666-4666-8666-666666666666',
    ...companyFranchiseDefaults,
    name: 'Levive',
    slug: 'levive',
    logo_url: '/imagens/clientes/levive.png',
    cover_image_url: null,
    segment: 'Saúde e estética',
    city: 'São Luís',
    state: 'MA',
    employees_range: '201-500',
    website_url: null,
    ...companyDistributionDefaults,
    instagram_url: null,
    linkedin_url: null,
    short_description: 'Empresa parceira com oportunidades em atendimento, comercial e suporte à operação.',
    about_text: 'A Levive atua com foco em experiência do cliente, atendimento consultivo e serviços de saúde e estética.',
    why_work_here: 'Plano de crescimento por área, liderança próxima e rotinas de treinamento.',
    culture_text: 'Ambiente disciplinado, acolhedor e orientado por qualidade.',
    page_status: 'published',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
];

export const mockJobs: Job[] = [
  {
    id: 'aaaaaaa1-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
    franchise_id: mockFranchises[0].id,
    company_id: mockCompanies[0].id,
    title: 'Assistente de Atendimento Infantil',
    slug: 'assistente-de-atendimento-infantil',
    short_description: 'Atendimento a famílias, organização de demandas e suporte à rotina da unidade.',
    description:
      'Atuar no atendimento a famílias, registrar solicitações, organizar informações e apoiar a liderança em rotinas operacionais.',
    about_job:
      'Vaga para atuar no suporte à rotina de atendimento infantil, com foco em organização, acolhimento e comunicação com famílias.',
    responsibilities: 'Atender famílias; registrar solicitações; acompanhar prazos; apoiar relatórios operacionais.',
    requirements: 'Ensino médio completo; boa comunicação; experiência com atendimento ou educação será diferencial.',
    desirable_requirements: 'Experiência com rotina escolar; facilidade com sistemas de atendimento; perfil organizado.',
    benefits: 'Vale-transporte; vale-alimentação; plano de desenvolvimento interno.',
    salary_range: 'R$ 1.600 a R$ 1.900',
    neighborhood: 'Renascença',
    city: 'São Luís',
    state: 'MA',
    modality: 'presencial',
    contract_type: 'clt',
    seniority: 'Júnior',
    education_level: 'Ensino médio - Completo',
    work_schedule: 'Para atuação em horário comercial.',
    about_company:
      'A Aba Kids atua com serviços voltados ao desenvolvimento infantil, combinando atendimento cuidadoso, rotina organizada e equipes preparadas.',
    status: 'open',
    is_featured: true,
    application_deadline: null,
    ...jobDistributionDefaults,
    salary_min: 1600,
    salary_max: 1900,
    created_at: now,
    updated_at: now,
    company: mockCompanies[0],
  },
  {
    id: 'aaaaaaa2-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
    franchise_id: mockFranchises[0].id,
    company_id: mockCompanies[1].id,
    title: 'Assistente Administrativo',
    slug: 'assistente-administrativo',
    short_description: 'Controle de documentos, indicadores e suporte às rotinas financeiras.',
    description:
      'Responsável por organizar documentos, acompanhar indicadores, apoiar processos financeiros e dar suporte à gestão.',
    about_job:
      'Vaga para apoiar rotinas administrativas e financeiras, mantendo documentos, controles e indicadores organizados.',
    responsibilities: 'Organizar documentos; apoiar contas a pagar; acompanhar indicadores; preparar relatórios.',
    requirements: 'Experiência administrativa; Excel intermediário; perfil organizado e analítico.',
    desirable_requirements: 'Vivência com rotinas financeiras; noções de indicadores; familiaridade com sistemas de gestão.',
    benefits: 'Vale-alimentação; assistência médica; bonificação por desempenho.',
    salary_range: 'R$ 2.200 a R$ 2.700',
    neighborhood: 'Cohama',
    city: 'São Luís',
    state: 'MA',
    modality: 'hibrido',
    contract_type: 'clt',
    seniority: 'Pleno',
    education_level: 'Ensino médio - Completo',
    work_schedule: 'Para atuação em horário comercial.',
    about_company: 'A Aquarela é uma empresa parceira com rotinas estruturadas, foco em atendimento e desenvolvimento de pessoas.',
    status: 'open',
    is_featured: true,
    application_deadline: null,
    ...jobDistributionDefaults,
    salary_min: 2200,
    salary_max: 2700,
    created_at: now,
    updated_at: now,
    company: mockCompanies[1],
  },
  {
    id: 'aaaaaaa3-aaaa-4aaa-8aaa-aaaaaaaaaaa3',
    franchise_id: mockFranchises[0].id,
    company_id: mockCompanies[4].id,
    title: 'Atendente de Loja',
    slug: 'atendente-de-loja',
    short_description: 'Atendimento ao cliente, organização de pedidos e apoio à rotina comercial.',
    description:
      'Atuar no atendimento aos clientes da Karolícias, apoiar pedidos, manter a organização do espaço e contribuir para uma experiência acolhedora.',
    about_job:
      'Vaga para atendimento em loja, com contato direto com clientes, apoio aos pedidos e organização do ambiente.',
    responsibilities: 'Atender clientes; organizar pedidos; apoiar exposição de produtos; manter o padrão de atendimento.',
    requirements: 'Boa comunicação, organização, disponibilidade de horário e interesse pelo segmento de alimentos.',
    desirable_requirements: 'Experiência anterior em loja; facilidade com vendas; vivência com atendimento presencial.',
    benefits: 'Vale-transporte; alimentação no local; treinamento interno.',
    salary_range: 'R$ 1.500 a R$ 1.900',
    neighborhood: 'Centro',
    city: 'São Luís',
    state: 'MA',
    modality: 'presencial',
    contract_type: 'clt',
    seniority: 'Operacional',
    education_level: 'Ensino médio - Completo',
    work_schedule: 'Para atuação em horário comercial.',
    about_company: 'A Karolícias atua no segmento de alimentos com foco em qualidade, apresentação, atendimento e ritmo operacional.',
    status: 'open',
    is_featured: true,
    application_deadline: null,
    ...jobDistributionDefaults,
    salary_min: 1500,
    salary_max: 1900,
    created_at: now,
    updated_at: now,
    company: mockCompanies[4],
  },
  {
    id: 'aaaaaaa4-aaaa-4aaa-8aaa-aaaaaaaaaaa4',
    franchise_id: mockFranchises[0].id,
    company_id: mockCompanies[3].id,
    title: 'Recepcionista',
    slug: 'recepcionista',
    short_description: 'Recepção de clientes, organização de agenda e suporte à rotina de atendimento.',
    description:
      'Recepcionar clientes do Darma Center, organizar agenda, registrar informações e apoiar o fluxo de atendimento.',
    about_job:
      'Vaga para recepção presencial, organização de agenda, acolhimento de clientes e suporte ao fluxo de atendimento.',
    responsibilities: 'Recepcionar clientes; organizar agenda; confirmar horários; apoiar rotinas administrativas.',
    requirements: 'Ensino médio completo; boa comunicação; experiência com recepção será diferencial.',
    desirable_requirements: 'Experiência em clínica ou estética; noções de caixa; conhecimento básico em sistemas de agenda.',
    benefits: 'Vale-transporte; bonificação; treinamento interno.',
    salary_range: 'R$ 1.600 a R$ 2.000',
    neighborhood: 'Calhau',
    city: 'São Luís',
    state: 'MA',
    modality: 'presencial',
    contract_type: 'clt',
    seniority: 'Operacional',
    education_level: 'Ensino médio - Completo',
    work_schedule: 'Para atuação em horário comercial.',
    about_company: 'O Darma Center reúne serviços com foco em bem-estar, atendimento humanizado e organização da experiência do cliente.',
    status: 'open',
    is_featured: false,
    application_deadline: null,
    ...jobDistributionDefaults,
    salary_min: 1600,
    salary_max: 2000,
    created_at: now,
    updated_at: now,
    company: mockCompanies[3],
  },
];

export const mockApplications: Application[] = [
  {
    ...applicationProcessDefaults,
    id: 'bbbbbbb1-bbbb-4bbb-8bbb-bbbbbbbbbbb1',
    franchise_id: mockFranchises[0].id,
    job_id: mockJobs[0].id,
    company_id: mockCompanies[0].id,
    candidate_name: 'Mariana Costa',
    candidate_email: 'mariana@example.com',
    candidate_phone: '(98) 99999-0001',
    candidate_city: 'São Luís',
    linkedin_url: null,
    portfolio_url: null,
    salary_expectation: 'R$ 1.900',
    availability: 'Imediata',
    message: 'Tenho experiência com atendimento presencial e canais digitais.',
    resume_file_path: 'applications/local/mariana-costa.pdf',
    status: 'novo',
    lgpd_consent: true,
    source: 'portal_publico',
    created_at: now,
    updated_at: now,
    job: mockJobs[0],
    company: mockCompanies[0],
  },
  {
    ...applicationProcessDefaults,
    stage: 'qualificacao',
    is_new: false,
    id: 'bbbbbbb2-bbbb-4bbb-8bbb-bbbbbbbbbbb2',
    franchise_id: mockFranchises[0].id,
    job_id: mockJobs[2].id,
    company_id: mockCompanies[4].id,
    candidate_name: 'Rafael Lima',
    candidate_email: 'rafael@example.com',
    candidate_phone: '(98) 98888-0002',
    candidate_city: 'São Luís',
    linkedin_url: 'https://linkedin.com',
    portfolio_url: 'https://portfolio.example.com',
    salary_expectation: 'R$ 1.900',
    availability: '30 dias',
    message: 'Tenho experiência com atendimento ao cliente e organização de pedidos.',
    resume_file_path: 'applications/local/rafael-lima.pdf',
    status: 'em_analise',
    lgpd_consent: true,
    source: 'portal_publico',
    created_at: now,
    updated_at: now,
    job: mockJobs[2],
    company: mockCompanies[4],
  },
];

export const mockProfiles: Profile[] = [
  {
    id: 'ccccccc1-cccc-4ccc-8ccc-ccccccccccc1',
    franchise_id: null,
    full_name: 'Administrador People Jobs',
    email: 'admin@peoplejobs.com.br',
    role: 'redde_super_admin',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'ccccccc2-cccc-4ccc-8ccc-ccccccccccc2',
    franchise_id: mockFranchises[0].id,
    full_name: 'Gestor Aba Kids',
    email: 'gestor@abakids.com.br',
    role: 'company_admin',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'ccccccc3-cccc-4ccc-8ccc-ccccccccccc3',
    franchise_id: mockFranchises[0].id,
    full_name: 'Recrutador Cliente',
    email: 'talentos@abakids.com.br',
    role: 'company_recruiter',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];

export const mockAccess: CompanyUserAccess[] = [
  {
    id: 'ddddddd1-dddd-4ddd-8ddd-ddddddddddd1',
    user_id: mockProfiles[1].id,
    company_id: mockCompanies[0].id,
    can_edit_company_page: true,
    can_manage_jobs: true,
    can_view_applications: true,
    can_download_resumes: true,
    created_at: now,
  },
  {
    id: 'ddddddd2-dddd-4ddd-8ddd-ddddddddddd2',
    user_id: mockProfiles[2].id,
    company_id: mockCompanies[0].id,
    can_edit_company_page: false,
    can_manage_jobs: true,
    can_view_applications: true,
    can_download_resumes: true,
    created_at: now,
  },
];

export const mockSiteContents: SiteContent[] = [
  {
    id: 'eeeeeee1-eeee-4eee-8eee-eeeeeeeeeee1',
    key: 'home_hero',
    title: 'Encontre oportunidades em empresas que contratam com mais critério.',
    subtitle:
      'O People Jobs conecta candidatos a empresas parceiras com processos de seleção mais claros, organizados e profissionais.',
    body: 'Veja vagas abertas em empresas parceiras do People Jobs e envie seu currículo de forma simples, rápida e segura.',
    button_label: 'Buscar vagas',
    button_url: '/vagas',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'eeeeeee2-eeee-4eee-8eee-eeeeeeeeeee2',
    key: 'home_company_cta',
    title: 'Sua empresa quer contratar com mais critério?',
    subtitle:
      'O People Jobs estrutura processos de contratação para reduzir improviso, rotatividade e decisões baseadas apenas em currículo.',
    body: null,
    button_label: 'Falar com a People Jobs',
    button_url: 'mailto:contato@peoplejobs.com.br',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];
